#!/usr/bin/env python3

import json
import re
import torch

TOKEN_PATTERN = re.compile(
    r"("
    r"\[[^\[\]]+\]"
    r"|Br"
    r"|Cl"
    r"|Si"
    r"|Se"
    r"|@@?"
    r"|%\d{2}"
    r"|."
    r")"
)

def tokenize_smiles(smiles):
    """
    Convert a SMILES string into SMILES-aware tokens.
    """

    tokens = TOKEN_PATTERN.findall(smiles)
    reconstructed = "".join(tokens)
    if reconstructed != smiles:
        raise ValueError(
            f"Tokenizer failed.\n"
            f"Original:      {smiles}\n"
            f"Reconstructed: {reconstructed}"
        )
    return tokens


def load_vocab(vocab_file):
    """
    Load vocabulary generated by Step 12.
    """
    with open(vocab_file, "r") as f:
        vocab = json.load(f)
    return vocab


def encode_smiles(smiles, vocab,):
    """
    Convert SMILES into:

        <BOS> tokens... <EOS>

    and then integer IDs.
    """
    tokens = tokenize_smiles(smiles)
    token_to_id = vocab["token_to_id"]
    special_ids = vocab["special_token_ids"]
    bos_id = special_ids["BOS"]
    eos_id = special_ids["EOS"]
    unk_id = special_ids["UNK"]

    ids = [bos_id]
    ids.extend(token_to_id.get(token,unk_id,) for token in tokens)
    ids.append(eos_id)
    return ids


def decode_ids(ids,vocab):
    """
    Convert token IDs back into a SMILES string.

    PAD/BOS are ignored.
    Decoding stops at EOS.
    """

    id_to_token = vocab["id_to_token"]
    special_ids = vocab["special_token_ids"]

    pad_id = special_ids["PAD"]
    bos_id = special_ids["BOS"]
    eos_id = special_ids["EOS"]

    tokens = []
    for token_id in ids:
        token_id = int(token_id)
        if token_id == eos_id:
            break
        if token_id in {pad_id, bos_id,}:
            continue
        token = id_to_token[str(token_id)]
        tokens.append(token)
    return "".join(tokens)